### ISSUE TITLE
Physical routing of MSMQ messages

### ISSUE THREAD

**Issue by mteinum** [SzymonPobiega/NServiceBus.Router#12]
Hi!

We have this setup

machines: A, B and C.

Machine |  Description
--------- | -----------
A | dotnet core running in docker using rabbitmq as transport
B | Router, with two interfaces: rabbitmq and MSMQ
B | Endpoint, Bar (.NET Framework)
C | Endpoint, Foo (.NET Framework)

Sending BarCommand from A via B Router to B Bar endpoints works great.

How can A send FooCommand to C (Foo) via B?

I have tried:
1.
```csharp
bridge.RouteToEndpoint(typeof(FooCommand), "Foo@C");
```
but this fails with invalid address

2. instance-mapping.xml in the router project.

```csharp
routerConfig.AddInterface<MsmqTransport>("MSMQ", t => {
  t.Routing().InstanceMappingFile().FilePath("instance-mapping.xml");
});
```

```xml
<?xml version="1.0" encoding="utf-8" ?>
<endpoints>
  <endpoint name="Foo">
    <instance machine="C"/>
  </endpoint>
</endpoints>
```
But the router still delivers FooCommand to its local machine Foo@B

**Comment by SzymonPobiega** [comment]
Hi

Please try following code in the router config:

```
var msmqIface = routerConfig.AddInterface<MsmqTransport>("MSMQ", t => {});
msmqIface.EndpointInstances.AddOrReplaceInstances("code-config", new List<EndpointInstance>()
{
   new EndpointInstance("Foo", null).AtMachine("C")
});
```

This should instruct the MSMQ transport to use machine C properly. The `InstanceMappingFile` API, although attached to the transport config, requires full NServiceBus as it is based on features which Router does not recognise. You need to use the lower level `EndpointInstances` API.

**Comment by robj-applied** [comment]
Hi Szymon,

I've been trying this exact scenario with your recommended code and for me, it still creates the message on the same machine that the router is on, rather than the remote machine (machine "C" in the example above).

Can I confim, what does the `"code-config"` bit do? I've copied it verbatim but perhaps wondering if I shouldn't have. Here's my router code for clarity:

```
const string sagaMsmqInterfaceName = "SAGA_MSMQ_INTERFACE";
            
var sagaMsmqInterface = routerConfig.AddInterface<MsmqTransport>(sagaMsmqInterfaceName, extensions => { });

var appServerSaga = new EndpointInstance(SagaEndpointName, null);
appServerSaga.AtMachine("REMOTE-MACHINE-NAME");

sagaMsmqInterface.EndpointInstances.AddOrReplaceInstances("code-config", new List<EndpointInstance>
{
	appServerSaga
});

sagaMsmqInterface.EnableMessageDrivenPublishSubscribe(CreateSqlSubscriptionStorage());
sagaMsmqInterface.AutoCreateQueues();
```

Using NServiceBus 7.2.2, and NServiceBus.Router 3.6.0

**Comment by robj-applied** [comment]
I've redone this using fresh endpoint names and now it works. Something must have got itself confused along the way.

**Comment by SzymonPobiega** [comment]
Hey hey. Sorry for the late reply. I was at a conference for last couple of days. Glad that it works now :)

**Comment by robj-applied** [comment]
No worries! Solved a fairly major problem so thanks for the original response :)
