### ISSUE TITLE
SqlSubscriptionStorage should use Func<Task<DbConnection>>

### ISSUE THREAD

**Issue by markgould** [SzymonPobiega/NServiceBus.Router#16]
SqlSubscriptionStorage currently takes a Func<DbConnection> which is problematic when there is async work to be done (in my case, acquiring an Access Token). It would be better if it was a Func<Task<DbConnection>>

The Sql Transport supports this (see UseCustomSqlConnectionFactory)

I'd be happy to submit a PR but naturally this would be a breaking change.

**Comment by SzymonPobiega** [comment]
@markgould the reason for this was that I copied the SQL persistence code to the Router and SQLP (for reasons unknown to me) uses `Func<DbConnection>`. I don't mind switching to `Func<Task>`. Let me see if it would be possible to do in a non-breaking way.

**Comment by SzymonPobiega** [comment]
@markgould I uploaded 3.5.0 which accepts either sync connection builder or an async one. The async version is expected to returned an already opened connection.

**Comment by markgould** [comment]
Looks great, thanks for implementing this so quickly!
