### ISSUE TITLE
ASB subscription/rule name shortener preventing subscription requests through NServiceBus Router

### ISSUE THREAD

**Issue by pihalve** [SzymonPobiega/NServiceBus.Router#25]
I’ve created an MSMQ based Publisher that can publish event messages to an Azure Service Bus based Subscriber. I order to accomplish this, I’ve implemented NServiceBus.Router into the publisher (running in same process). This works fine. Subscriber can send subscription request and publisher stores it in subscription storage as originating from router. Publisher can publish event messages to subscriber.

However, for subscriptions where subscription/rule name exceeds 50 characters, at which point the name shorteners kicks in, then the subscription request is not picked up by the publisher, and it is not stored in subscription storage, which means publisher cannot publish event messages for that type.

Any way to fix this?

**Comment by SzymonPobiega** [comment]
@pihalve which topology are you using in the ASB transport?

**Comment by pihalve** [comment]
It is the forwarding topology. It is my understanding that this is the only one supported. Well at least in the newest version of NServiceBus.Transport.AzureServiceBus. Basically I use newest versions of all packages involved.

**Comment by SzymonPobiega** [comment]
Thnaks. I'll try to repro this in an acceptance test and see what can be done.

**Comment by SzymonPobiega** [comment]
In https://github.com/SzymonPobiega/NServiceBus.Router/commit/5ff75c6168123e6a35d1b736638a001a1877df86 I added an acceptance test as an attempt to repro the issue but it seems to work fine. I am using the forwarding topology with sanitization enabled. The name of the subscription is based on a hash but the event is still delivered. I am probably missing something. Can you create a PR with modifications required to break it? Then I should be able to fix it.

**Comment by pihalve** [comment]
I finally found the problem. You are right, it works fine :) For some reason I forgot a call to RegisterPublisher() for that specific event message type in the subscriber. I guess I was too focused on the name shortening to notice this. Sorry for the inconvenience.

**Comment by SzymonPobiega** [comment]
@pihalve No problem! That test is a good addition anyway :-)
