### ISSUE TITLE
"poison" table no longer created

### ISSUE THREAD

**Issue by rioka** [SzymonPobiega/NServiceBus.Router#30]
While upgrading NServiceBus in an application, we realised table _poison_ (whatever name it is assigned via `PoisonQueueName`) is no longer created.

### Steps to reproduce
- Use sample [update-and-publish](https://github.com/Particular/docs.particular.net/tree/master/samples/router/update-and-publish) solution.
- Build (as of now, it will use NServiceBus 7.3.0 via NServiceBus.Router 3.8.0)
- Start `Router`

|Expected result|Actual result|
|-|-|
|table `poison` being created|no `poison` table found|

When forcing references to previous packages ie 
- NServiceBus v7.2.*
- NServiceBus.Router v3.7.*

 everything works as expected

**Comment by SzymonPobiega** [comment]
Hey @rioka 

This issue has actually been fixed here https://github.com/SzymonPobiega/NServiceBus.Raw/issues/13 but I didn't release the new patch to Router. Try explicitly referencing `NServiceBus.Raw` 3.2.1 in your project and it should fix the issue. In the meantime I'll release Router 3.8.1 that bumps the minim version of Raw.
