### ISSUE TITLE
Transform messages

### ISSUE THREAD

**Issue by Adam-MagmaSw** [SzymonPobiega/NServiceBus.Router#32]
Hi,

Is there a way to configure the router to transform messages on the way through? I can see there are Rules which look like they might be useful but I can't tell whether the messages are immutable from within a rule.

Thanks

Adam

**Comment by SzymonPobiega** [comment]
Hi @Adam-MagmaSw 

The Router has not been designed with this use case in mind but I am pretty sure it is doable using a rule in the `PreroutingContext`. This is the only stage of the routing engine that allows replacing the body (as `byte[]`). Further down the line the body is `readonly`. I haven't tested this myself, though.

An alternative would be to use a simple `NServiceBus.Raw` endpoint or full `NServiceBus` endpoint. The downside of the former is the fact that is very low level.

**Comment by Adam-MagmaSw** [comment]
Thanks for getting back to me Szymon

**Comment by gursharan001** [comment]
Hello, just a comment on this. We were wanting to do something similar - JSON <-> XML. In pre-routing, body can be changed but not the headers. In post-routing, headers can be changed but not the body. So how do I change content type header and body at the same time?
