### ISSUE TITLE
Enable on SendOnly endpoints

### ISSUE THREAD

**Issue by dmarckmann** [SzymonPobiega/NServiceBus.Router#8]
Exception "LocalAddress isn't available since this endpoint is configured to run in send-only mode." is thrown. 

Is it possible to enable sendonly endpoints?

My configration looks like this:

    busConfiguration.SendOnly();
    var transport = busConfiguration.UseTransport<RabbitMQTransport>()
        .ConnectionString(ConfigurationManager.ConnectionStrings["NServiceBus/Transport"].ConnectionString)
        .TimeToWaitBeforeTriggeringCircuitBreaker(TimeSpan.FromMinutes(10))
        .UseConventionalRoutingTopology();
    var routing = transport.Routing();

    var routedRouting = routing.ConnectToRouter("Transport.Bridge");
    routedRouting.RouteToEndpoint(typeof(AddActionableCommand), "Actionables.Service");

Thx

**Comment by SzymonPobiega** [comment]
Hi @dmarckmann 

I merged your PR. :bow: ❤️ . It has been released as 3.2.0.
